name: CI

# Trigger on push to main and manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: adityamalagi
          password: ${{ secrets.GHCR_PAT }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/adityamalagi/production-devops-platform:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/adityamalagi/production-devops-platform:latest

